# Generated by Django 3.2 on 2022-06-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_producer_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
